# Generated by Django 4.0.4 on 2022-06-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcode',
            name='quizcode_date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizcode',
            name='quizcode_time',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
