# Generated by Django 4.0.4 on 2022-08-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_quizcode_quizcode_date_quizcode_quizcode_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdatafb',
            name='correctans',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quizdatafb',
            name='question',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
