# Generated by Django 4.0.4 on 2022-08-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_alter_quizdatafb_correctans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcode',
            name='quizcode_date',
        ),
        migrations.RemoveField(
            model_name='quizcode',
            name='quizcode_time',
        ),
        migrations.AddField(
            model_name='quizcode',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizcode',
            name='quiz_topic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizcodefb',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizcodefb',
            name='quiz_topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
