# Generated by Django 4.0.4 on 2022-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_remove_quizcode_quizcode_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='percentagee',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
