# Generated by Django 4.0.4 on 2022-08-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_studentmarks_percentagee'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCodeTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('quizcode', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('quiz_topic', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizDataTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000, null=True)),
                ('false', models.CharField(max_length=20, null=True)),
                ('true', models.CharField(max_length=20, null=True)),
                ('qquizcode', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
