# Generated by Django 4.0.4 on 2022-08-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_quizcodetf_quizdatatf'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdatatf',
            name='correctans',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
